
#修改文件上传的大小
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  datasource:
    druid:
      mysql:
#         解决druid 日志报错：discard long time none received connection:xxx
        usePingMethod: false

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Item?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: wai
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 192.168.100.100
    port: 6379




server:
  port: 8081
  max-http-header-size: 81920
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spring.entity
  configuration: #指定mybaits全局配置
    map-underscore-to-camel-case: true
    use-generated-keys: true



file:
  path: C:\Users\86183\Desktop\file\








